# NUMPY 

## Why Numpy 

In [1]:
# Numpy is a python library just as the list in python, but it is used more often as campare to the python list because --
# 1) Numpy is written in C languge, a really fast language so numpy does the work fast as compare to list 
# 2) Machine only knows the binary language and with numpy its really easy to convert data to binary
# 3) Numpy do vectorisation via broadcasting (easily speaking it avoid loops)
# These reasons makes numpy suitable for machine learning and data science 

In [2]:
import numpy as np 

## 1) Datatypes and Attributes 

In [3]:
# numpy basic data type is a ndarray 
array = np.array([1,2,3])
array

array([1, 2, 3])

In [4]:
type(array)

numpy.ndarray

In [5]:
# 2 dimensional array 
array_2 = np.array([[1,2,3],
                  [2,3,4]])
array_2

array([[1, 2, 3],
       [2, 3, 4]])

In [6]:
# Shape is an attribute to check the rows and columns of the array 
array_2.shape

(2, 3)

In [7]:
array_3 = np.array([[1,2,3],
                   [2,3,4],
                   [3,4,5]])
array_3

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [8]:
array_3.shape 

(3, 3)

In [9]:
# A 3 dimensional array 
array_4 = np.array([[[1,2,3],
                   [2,3,4]], 
                   
                   [[12,13,14],
                    [1,2,3]]])

In [10]:
array_4

array([[[ 1,  2,  3],
        [ 2,  3,  4]],

       [[12, 13, 14],
        [ 1,  2,  3]]])

In [11]:
array_4.shape

(2, 2, 3)

In [12]:
array.shape

(3,)

In [13]:
# ndim is a attribute to check the dimension of the array 
array.ndim , array_2.ndim , array_4.ndim

(1, 2, 3)

In [14]:
# dtype to check the data type of the array 
# size to check the size of the arrary
print(array.dtype)

array.size

int32


3

In [15]:
# Creating a dataframe from a numpy array 
import pandas as pd 

In [16]:
df = pd.DataFrame(array_3)

In [17]:
df 

0  1  2
0  1  2  3
1  2  3  4
2  3  4  5

## 2) Creating Numpy arrays 

In [18]:
# "ones is a function to create an array of 1 of your own size"
ones = np.ones((2,3), dtype = int )

In [19]:
ones 

array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
# Use shift and tab and click on the function to see the documentation of the function 

In [21]:
type(ones)

numpy.ndarray

In [22]:
range_array = np.arange(0,10,2)

In [23]:
# Function to create an array of the numbers in the given range 
range_array

array([0, 2, 4, 6, 8])

In [24]:
# random.randint is a function to create an array of the given size of with random number in the given range 
random_array = np.random.randint(0, 5 , size = (2,2))

In [25]:
random_array

array([[0, 0],
       [3, 1]])

In [26]:
# random.random is a function to create and array of given size with numbers in the range of  0 to 1 
random__2 = np.random.random((2,2))
random__2


array([[0.45333008, 0.3995727 ],
       [0.62040263, 0.55135297]])

In [27]:
# So the number generated by the computer are not actual random numbers, they are psuedo random numbers 
# i.e they are genrated by an algorithm and that algorithm is based upon a number (any number) known as the seed 

# So using the function random.seed () we can generate same set random number again and again 

In [28]:
np.random.seed(7)
random_number_2 = np.random.randint(0,5,size = (4,4))

In [29]:
random_number_2

array([[4, 1, 3, 3],
       [4, 1, 0, 1],
       [2, 2, 0, 4],
       [0, 4, 0, 3]])

## 3) Viewing arrays and matrices 

In [30]:
# Function to find the unique number in an array 
np.unique(random_number_2)

array([0, 1, 2, 3, 4])

## 4) Manipulating Arrays 

### Arithemetic 

In [31]:
# Adding two arrays 
one_array = np.array([1,2,3])

In [32]:
second_array = np.array([2,3,4])


In [33]:
one_array + second_array 

array([3, 5, 7])

In [34]:
one_array + 1 


array([2, 3, 4])

In [37]:
third_array = np.array ([2,3,2])
one_array + third_array 

array([3, 5, 5])